name = 'tomstheme'
license = 'MIT'
licenselink = 'https://github.com/tomdvies/tomdvies.com/LICENSE'
description = 'Theme description'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/tomdvies/tomdvies.com'

# If you have a running demo of the theme
demosite = 'https://tomdvies.com'

# Taxonomy terms
tags = ['blog', 'basic']
features = ['no js', 'javascript not here', 'katex']


# If the theme has a single author
[author]
  name = 'Tom'
  homepage = 'tomdvies.com'

